# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/TestRunning-0.1.0-Linux
Summary:        Banking application test framework
Name:           testrunning-devel
Version:        0.1.0
Release:        1
License:        MIT
Group:          Development/Tools
Vendor:         alexvsl2007















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename TestRunning-0.1.0-Linux.rpm
%define _unpackaged_files_terminate_build 0





%description
A simple C++ library for printing messages


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
/usr/bin/RunTest
/usr/include/Account.h
/usr/include/Transaction.h
%dir /usr/include/gmock
/usr/include/gmock/gmock-actions.h
/usr/include/gmock/gmock-cardinalities.h
/usr/include/gmock/gmock-function-mocker.h
/usr/include/gmock/gmock-matchers.h
/usr/include/gmock/gmock-more-actions.h
/usr/include/gmock/gmock-more-matchers.h
/usr/include/gmock/gmock-nice-strict.h
/usr/include/gmock/gmock-spec-builders.h
/usr/include/gmock/gmock.h
%dir /usr/include/gmock/internal
%dir /usr/include/gmock/internal/custom
/usr/include/gmock/internal/custom/README.md
/usr/include/gmock/internal/custom/gmock-generated-actions.h
/usr/include/gmock/internal/custom/gmock-matchers.h
/usr/include/gmock/internal/custom/gmock-port.h
/usr/include/gmock/internal/gmock-internal-utils.h
/usr/include/gmock/internal/gmock-port.h
/usr/include/gmock/internal/gmock-pp.h
%dir /usr/include/gtest
/usr/include/gtest/gtest-assertion-result.h
/usr/include/gtest/gtest-death-test.h
/usr/include/gtest/gtest-matchers.h
/usr/include/gtest/gtest-message.h
/usr/include/gtest/gtest-param-test.h
/usr/include/gtest/gtest-printers.h
/usr/include/gtest/gtest-spi.h
/usr/include/gtest/gtest-test-part.h
/usr/include/gtest/gtest-typed-test.h
/usr/include/gtest/gtest.h
/usr/include/gtest/gtest_pred_impl.h
/usr/include/gtest/gtest_prod.h
%dir /usr/include/gtest/internal
%dir /usr/include/gtest/internal/custom
/usr/include/gtest/internal/custom/README.md
/usr/include/gtest/internal/custom/gtest-port.h
/usr/include/gtest/internal/custom/gtest-printers.h
/usr/include/gtest/internal/custom/gtest.h
/usr/include/gtest/internal/gtest-death-test-internal.h
/usr/include/gtest/internal/gtest-filepath.h
/usr/include/gtest/internal/gtest-internal.h
/usr/include/gtest/internal/gtest-param-util.h
/usr/include/gtest/internal/gtest-port-arch.h
/usr/include/gtest/internal/gtest-port.h
/usr/include/gtest/internal/gtest-string.h
/usr/include/gtest/internal/gtest-type-util.h
%dir /usr/lib/cmake
%dir /usr/lib/cmake/GTest
/usr/lib/cmake/GTest/GTestConfig.cmake
/usr/lib/cmake/GTest/GTestConfigVersion.cmake
/usr/lib/cmake/GTest/GTestTargets-release.cmake
/usr/lib/cmake/GTest/GTestTargets.cmake
/usr/lib/libgmock.a
/usr/lib/libgmock_main.a
/usr/lib/libgtest.a
/usr/lib/libgtest_main.a
%dir /usr/lib/pkgconfig
/usr/lib/pkgconfig/gmock.pc
/usr/lib/pkgconfig/gmock_main.pc
/usr/lib/pkgconfig/gtest.pc
/usr/lib/pkgconfig/gtest_main.pc




%changelog
* Sat May 24 2025 alexvsl2007 <alexvsl2007@gmail.com> 0.1.0.0
- Initial RPM release



