name: Docker Build and Test

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t lab08-app:latest .
        
    - name: Run container and extract artifacts
      run: |
        mkdir -p artifacts

        docker run --name lab08-container lab08-app:latest
        docker cp lab08-container:/output/. artifacts/

        ls -la artifacts/
        cat artifacts/test_results.log
        
        docker --version > artifacts/docker-version.txt
        docker-compose --version >> artifacts/docker-version.txt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          artifacts/*.tar.gz
          artifacts/test_results.log
          artifacts/docker-version.txt
        if-no-files-found: error
