name: Docker Build

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install docker
      run: |
        sudo apt-get remove containerd.io
        sudo apt install docker.io docker-compose -y
        
    - name: Build Docker image
      run: docker build -t lab08-app .
      
    - name: Run container and extract artifacts
      run: |
        mkdir -p artifacts
        docker run --name lab08-container lab08-app
        docker cp lab08-container:/output/. artifacts/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: artifacts/
